### ISSUE TITLE
Samples The method isVisible() is undefined for the type DoubleDataSet  

### ISSUE THREAD

**Issue by tsatatwer** [fair-acc/chart-fx#510]
Hi ,

I get this  **dataSet2.isVisible() in the samples  in class VisibilityToggleSampl**e
**The method isVisible() is undefined for the type DoubleDataSet**

**Comment by wirew0rm** [comment]
Hey,

that's weird, 'DoubleDataSet' extends 'AbstractDataSet' which implements 'isVisible()'.

Can you give some more information on how you are building chart-fx (os, are you using an IDE, versions of chartfx, maven, java)? Also please recheck if your IDE maybe "fixed" some includes or something like that by checking `git diff` output and maybe running 'mvn build' directly from the command line.

**Comment by tsatatwer** [comment]
Hi ,
sorry for the delay , my IDE is eclipse 2022-03 I just import the examples as maven project it was really difficult import with several errors I wish if you could make it easy to create a new project for this great library and very productive one indeed , I get this error and very silly solution to me just to comment the line cause that is .

**Comment by wirew0rm** [comment]
We'll try to simplify our build system with the 11.3 release a bit and also do some testing in IDE compatibility, but apart that there is nothing concrete that I can offer on this issue. It seems that you found a solution that works for you, otherwise don't hesitate to reopen the issue with additional information.
