### ISSUE TITLE
NoSuchMethodError: 'void javafx.scene.canvas.GraphicsContext.setImageSmoothing(boolean)'

### ISSUE THREAD

**Issue by crowlogic** [fair-acc/chart-fx#550]
Latest JavaFX from JDK-19

Caused by: java.lang.NoSuchMethodError: 'void javafx.scene.canvas.GraphicsContext.setImageSmoothing(boolean)'
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.renderer.spi.ContourDataSetRenderer.drawHeatMap(ContourDataSetRenderer.java:200)
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.renderer.spi.ContourDataSetRenderer.paintCanvas(ContourDataSetRenderer.java:383)
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.renderer.spi.ContourDataSetRenderer.render(ContourDataSetRenderer.java:433)
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.XYChart.redrawCanvas(XYChart.java:433)
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.Chart.layoutChildren(Chart.java:756)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1204)

**Comment by wirew0rm** [comment]
Since JDK9 javafx is called openjfx and distributed independently from the JDK (although some distributions and jdk vendors bundle it into their versions of the JDK). While we have not kept up with new openjfx versions (still using openjfx 13), until now there where not API changes preventing chart-fx to be used with newer releases of openjfx. According to the documentation, the function in question is still available in the newest (19) release of openjfx (and has been since 12):
https://openjfx.io/javadoc/19/javafx.graphics/javafx/scene/canvas/GraphicsContext.html#setImageSmoothing(boolean)

Can you check again where your javafx is coming from and which version it is?

**Comment by crowlogic** [comment]
/home/crow/.m2/repository/org/openjfx/javafx-base/13.0.1/javafx-base-13.0.1.jar
/home/crow/.m2/repository/org/openjfx/javafx-base/13.0.1/javafx-base-13.0.1-linux.jar
/home/crow/.m2/repository/org/openjfx/javafx-controls/13.0.1/javafx-controls-13.0.1.jar
/home/crow/.m2/repository/org/openjfx/javafx-controls/13.0.1/javafx-controls-13.0.1-linux.jar
/home/crow/.m2/repository/org/openjfx/javafx-graphics/11/javafx-graphics-11.jar
/home/crow/.m2/repository/org/openjfx/javafx-graphics/11/javafx-graphics-11-linux.jar
/home/crow/.m2/repository/org/openjfx/javafx-media/11/javafx-media-11.jar
/home/crow/.m2/repository/org/openjfx/javafx-media/11/javafx-media-11-linux.jar
/home/crow/.m2/repository/org/openjfx/javafx-web/11/javafx-web-11.jar
/home/crow/.m2/repository/org/openjfx/javafx-web/11/javafx-web-11-linux.jar

**Comment by crowlogic** [comment]
Fixed it, the problem was the version of org.controlsfx that was being imported

changed from version 11.0.0 to 11.1.1

		<dependency>
			<groupId>org.controlsfx</groupId>
			<artifactId>controlsfx</artifactId>
			<version>11.1.1</version>
		</dependency

**Comment by crowlogic** [comment]
might be something to mention in the README, or maybe it was and I overlooked it

**Comment by wirew0rm** [comment]
Glad that it works for you know and thanks for sharing your findings!
I don't think it is mentioned in the README, but I also don't understand how the error message relates to the controlsfx version (not to say that it isn't related, I just don't see how the problem was caused). But anyway we should update controlsfx since there where a lot of improvements made by them that we are missing out on.

**Comment by crowlogic** [comment]
> Glad that it works for you know and thanks for sharing your findings!
> I don't think it is mentioned in the README, but I also don't understand how the error message relates to the controlsfx version (not to say that it isn't related, I just don't see how the problem was caused). But anyway we should update controlsfx since there where a lot of improvements made by them that we are missing out on.

No problem,  you can run the project at http://github.com/crowlogic/arb4j , I've just now started integrating chartfx
