### ISSUE TITLE
Missing Class

### ISSUE THREAD

**Issue by Scarraluba** [fair-acc/chart-fx#563]
java: cannot find symbol
symbol:   class MultiArrayDouble
location: package io.fair_acc.dataset.spi.utils

 - JavaFx version: 
 - ChartFx version: [master, 11.2.2, ...]

**Comment by wirew0rm** [comment]
The file should be autogenerated by maven via the chartfx-generate plugin.

``` bash
mvn compile # should work on the command line ootb
mvn -pl chartfx-generate install  # needed for some ide's that don't look up plugins in the multi module project
```

**Comment by Scarraluba** [comment]
how do i do that..

C:\Users\sphel>mvn install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.203 s
[INFO] Finished at: 2022-12-11T16:50:38+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\sphel). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by wirew0rm** [comment]
Sorry for the super late response.

This to me looks like an unrelated error with your IDE. I have no experience with Android Studio (even less on windows) so I'm afraid I can't help much here.
You could try skipping the generation of javadocs, maven has a command line flag for that.

I'm closing this for now since there isn't much we can do on our side (short of checking the autogenerated code into git or remove the codegeneration completely). But I'll do a section in the readme describing the problem and listing some workarounds.

If you have any more findings feel free to share them here.
