### ISSUE TITLE
Listener to react on mouse clicks on data points

### ISSUE THREAD

**Issue by thhart** [fair-acc/chart-fx#567]
### Discussed in https://github.com/fair-acc/chart-fx/discussions/431

I think this is a very helpful feature in general  and worth to be integrated in the code as standard.

<div type='discussions-op-text'>

<sup>Originally posted by **magicroomy** June 16, 2021</sup>
I am looking for an example to establish a listener to react on the user clicking on a single data point (Entry in a dataset). So I could direct the user to the "detail" of the point in another window.
If it is important: I use DoubleErrorDataSets in XY Graphs.
</div>

**Comment by wirew0rm** [comment]
Please do not duplicate discussions into issues.

I'll close this one, not because I don't agree that this would be a useful feature, but at least we won't have time in the immediate future to work on this and the discussion on how to implement such a feature can be kept in the existing topic so that everything is in one place. If you want to work on implementing this feature in chartfx, feel free to discuss there and/or open a (draft) PR to get feedback.
