### ISSUE TITLE
getXValues/getYValues returns extra values not included in the data

### ISSUE THREAD

**Issue by hewitta** [fair-acc/chart-fx#572]
**Describe the bug**
Using getXValues() or getYValues from a DoubleDataSet object appends numerous 0.0 values at the end of the returned array.

**Environment:**
 - OS: Windows 11
 - Java version: 19
 - JavaFx version: 19
 - ChartFx version: 11.2.7

**Comment by wirew0rm** [comment]
Hey. This is by design and allows to efficiently add and remove points from the dataset by allocating bigger arrays than necessary so that not every single add/remove operation triggers a reallocating and copying of the data. `getXValues()` provides raw access to this backing array (otherwise it would have to copy it to a new array -> allocation + copy costs) such that `dataset.getXValues()[i], i in [0, dataset.getDataCount()]` contains the data.

I'll add a note to add this to the function's documentation.

**Comment by hewitta** [comment]
I see. And the trim() method under the DoubleDataSet object is used to remove the zeros prior to pulling the xValues or yValues, correct?
